### ISSUE TITLE
NoSQL

### ISSUE THREAD

**Issue by cjackie** [Wolfie-Home/Documents#10]
@kbumsik 
I was reading something about Google's BigTable DB, which is a NoSQL. MongoDB is also NoSQL. Those companies are generating a lot revenue and absorb a lot of venture capitals. Could you do some research about it, and find out:
- what is it?
- is it populare? why popular(because of big data)?
- compare and contrast with SQL language.
- more points you want to explain

I know you like SQL language, because there is a standard. loll. but um, knowing what is available now, will be useful. Our project might take advantage of it.

If you have time, and you are interested in it.

**Comment by kbumsik** [comment]
@cjackie 
I was actually researching about NoSQLs like MongoDB when I was considering on  which DB we will use.
Although I haven't fully understand about NoSQL, let me tell you things I know so far:

RDBMSs like MySQL and SQLite uses structured datatables. RDBMS emphasis on ACID properties (Atomicity, Consistency, Isolation, Durability). All data in a RDBMS has structured relationships in a way DB designers made. All data in RDBMS should be categorized well . 

However, in real life, not all data have relationships nor well structured. That's the reason why NoSQL came out. "No"SQL does not mean it is not SQL. NoSQL (non-relational SQL or 'not only' SQL) does not use relational tables. Instead, NoSQL usually stores data in key/value-based (like JSON, key and value). MongoDB is called Document-based DB, and 'Document' here is JSON-like document. Although NoSQL lacks ACID properties, it let you store any kinds of data in the storage and these data is always available to client (it is called CAP properties). For example, Google made NoSQL firstly for their search engine because RDBMS is too static to scrape all kinds of text of websites around the world. In matter of complexity, RDBMS data scales vertically, meaning you need to keep adding new structures when DB gets bigger. On the other hand, NoSQL is very popular in Data Science because it let you store any kinds of data horizontally so that they are able to analyze data in any way. NoSQL is also interesting topic in Internet of Things too, IoT field can take advantage of data of 'Things'.

In my conclusion, NoSQL did not come to replace the whole features of RDBMS. They are different. RDBMS strives where all data should be structured (think about Users, Locations, Devices in our project), like most of common websites. However, NoSQL plays a big role where data is not always structured. So in our project, we could take advantage of NoSQL for our device's data storage (values of parameters). It will be very useful when we want to introduce something like machine learning or data analytics based on device's data.

So it NoSQL is worth considering. But I will do what I can do best first. When the backbone of our project is quite completed I will definitely try to figure out how MongoDB can integrate into our project.

**Comment by cjackie** [comment]
Actually, I have used MongoDB before in freshman year. The reason was that I could easily interact with DB with Javascript like syntax.

Your explanation makes sense. structure data vs un-structure data is the main difference. Nice job!

**Comment by kbumsik** [comment]
Oh that's sounds interesting. Do you have any useful learning material when you used MongoDB?

**Comment by cjackie** [comment]
I only used documentation provided in MongoDB website. I was trying to use, without understanding much about ti.
